alpaca_eval_qwen2_fn:
  prompt_template: "alpaca_eval_qwen2_fn/ranking_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "qwen2"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "ranking_parser"
  batch_size: 1
