compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED  # MULTI_GPU DEEPSPEED FSDP
deepspeed_config:
  deepspeed_multinode_launcher: standard
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  # fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  # fsdp_transformer_layer_cls_to_wrap: MistralDecoderLayer
  fsdp_use_orig_params: true
downcast_bf16: 'no'
gpu_ids: all
main_training_function: main
mixed_precision: bf16
rdzv_backend: c10d
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

num_processes: 8
num_machines: 1
